name: Build ARMv7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for ARMv7
        run: |
          CGO_ENABLED=0 \
          GOOS=linux \
          GOARCH=arm \
          GOARM=7 \
          go build -o fast-note-sync-service .

          tar -zcvf fast-note-sync-service-linux-armv7.tar.gz fast-note-sync-service

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fast-note-sync-service-linux-armv7
          path: fast-note-sync-service-linux-armv7.tar.gz